### PR TITLE
Added I/O redirection

### PR DESCRIPTION
**Pull request by BuzzHari**
Added '<' , '>', '2>', '2>&1'.

### CODE REVIEW

**Comment by BuzzHari** [comment]
I am sorry, I don't really know how to fix the CodeFactor issue. I am assuming it's because of all those 'if' conditions?

**Comment by xorz57** [comment]
@BuzzHari You did a great job! Don't worry about the CodeFactor check. It just says that the parse function is very complex so we could deal with that by splitting the code a bit into more functions.

**Comment by BuzzHari** [comment]
Ohh okay, Is there any other problems with it or any changes you need?

**Comment by xorz57** [comment]
@BuzzHari No, it is ok! Just give me some time because I am busy with University. I will review your code. Probably will merge this one as well! :)

**Comment by xorz57** [comment]
@BuzzHari, thanks for your contribution! 🍻

**Pull request merged**
